---
title: "Untitled"
author: "Julián Ospina"
date: "15/1/2022"
output: html_document
---

```{r include=FALSE}
library(reticulate)
library(readxl)
library(ggplot2)
library(DT)
library(kableExtra)
library(tidyverse)
library(knitr)
library(sqldf)
library(reticulate)
library(FSinR)
library(caret)
library(hash)
library(plotly)
load('RUNT.RData')
```

```{r}
fechas <- read_excel("autos.xlsx")
fechas <- fechas$Fecha
```


```{python, include=FALSE}
import pandas as pd
import numpy as np
from sklearn import preprocessing
import tensorflow as tf
from keras.models import Sequential
from keras.layers.core import Dense
import pyreadr
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
```

```{python}
result = pyreadr.read_r('RUNT.RData')
df = result["db"]
```

```{python}
from sklearn.preprocessing import StandardScaler
X = df[["dia","mes","anno","dia_semana","semana","TRM","Laboral"]]
scale = StandardScaler()
X =  scale.fit_transform(X)
print(X)
y = df["Unidades"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
```

```{python}
print(max(y))
```


```{python}
from keras import backend as K

def coeff_determination(y_true, y_pred):
    from keras import backend as K
    SS_res =  K.sum(K.square( y_true-y_pred ))
    SS_tot = K.sum(K.square( y_true - K.mean(y_true) ) )
    return ( 1 - SS_res/(SS_tot + K.epsilon()) )
```



```{python}
model = Sequential()
model.add(Dense(10, input_dim=7,kernel_initializer='he_uniform', activation='relu'))
model.add(Dense(1,  activation='relu'))
```

```{python}
model.compile(loss='mse',
              optimizer='adam',
              metrics=[coeff_determination])
```

```{python}
model.fit(X_train, y_train, epochs=15000, batch_size=100,verbose=0, validation_split=0.3,shuffle=True)
```
```{python}
r2Training = model.evaluate(X_train,y_train)
r2Testing = model.evaluate(X_test,y_test)
print("Train: {} \nTest: {}".format(r2Training[1],r2Testing[1]))
```
```{python}
pred = model.predict(X)
```

```{r}
resultado <- data.frame(fecha = fechas, 
                         Observado = py$y, 
                         Predicho = py$pred)
resultado_plot <- pivot_longer(resultado, 
                                cols = c("Predicho", "Observado"),
                                names_to = "curva",
                                values_to = "total")
plot <- ggplot(data = resultado_plot,
         aes(x = fecha, y = total, 
         group = curva, 
         color = curva)) +
    geom_line() +
    ggtitle("Datos observados vs datos predichos") +
    labs(y = "Vehículos registrados", x = "Fecha") + 
    theme(plot.title = element_text(hjust = 0.5)) +
    labs(color = "Curva") + 
    scale_color_manual(values=c("Red", "Blue"))
   
ggplotly(plot)
```
```{r}
#save(resultado,file = "PredObNN.RData")
```




