---
title: "Untitled"
author: "Julián Ospina"
date: "15/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
load('RUNT.RData')
```

```{r}
db
```


```{python}
import pandas as pd
import numpy as np
from sklearn.svm import SVR
from sklearn.svm import LinearSVR
from sklearn import preprocessing
import pyreadr
from sklearn.model_selection import train_test_split
```

```{python}
result = pyreadr.read_r('RUNT.RData')
df = result["db"]
```

```{python}
X = df[["dia","mes","anno","dia_semana","semana","TRM","Laboral"]]
y = df["Unidades"]
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
```
```{python}
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X_train = scale.fit_transform(X_train) 
scale = StandardScaler()
X_test = scale.fit_transform(X_test)
```

```{python}
model = LinearSVR(epsilon=0.2, tol=1e-5, loss='squared_epsilon_insensitive')
model.fit(X_train,y_train)
```
```{python}
model.score(X_train,y_train)
model.score(X_test,y_test)
```







